export class ErrMessageUtilsTH{

    messageSuccess ='เรียบร้อย'

    errVisitorSlotRunningIdNotFound = 'ไม่พบ visitor_slot_running_id'
    errVisitorSlotRunningIdNotNumber = 'visitor_slot_running_id ต้องเป็นตัวเลขเท่านั้น'
    errVisitorCartypeIDNotfound = 'ไม่พบรหัสประเภทรถ'
    errVisitorCartypeIDNotNumber = 'รหัสประเภทรถต้องเป็นตัวเลขเท่านั้น'
    errVisitorCartypeNameContractionNotFound = 'ไม่พบอักษรย่อของประเภทรถ'
    errVisitorCartypeNameContractionProhibitSpecial ='อักษรย่อของประเภทรถ ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorCartypeNameThNotFound = 'ไม่พบประเภทรถ (ชื่อไทย)'
    errVisitorCartypeNameThProhibitSpecial = 'ประเภทรถ (ชื่อไทย) ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorCartypeNameEnNotFound = 'ไม่พบประเภทรถ (ชื่ออังกฤษ)'
    errVisitorCartypeNameEnProhibitSpecial = 'ปรเภทรถ (ชื่ออังกฤษ) ห้ามมีอักขระพิเศษหรือช่องว่าง'
    
    errVisitorInfoNotFound = 'ไม่พบข้อมูลของ Visitor'
    errVisitorInfoPrefixNameNotFound = 'ไม่พบคำนำหน้าชื่อ Visitor'
    errVisitorInfoPrefixNameProhibitSpecial = 'คำนำหน้าชื่อ Visitor ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorInfoFirstNameNotFound = 'ไม่พบชื่อของ Visitor'
    errVisitorInfoFirstNameProhibitSpecial = 'ชื่อของ Visitor ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorInfoLastNameNotFound = 'ไม่พบนามสกุลของ Visitor'
    errVisitorInfoLastNameProhibitSpecial = 'นามสกุลของ Visiotr ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errVisitorInfoBirthDateNotFound = 'ไม่พบวัน-เดือน-ปี เกิด ของ Visitor'
    errVisitorInfoIdentityNotFound = 'ไม่พบรหัสประจำตัวประชาชน'
    errVisitorInfoIdentityNotNumber = 'รหัสประจำตัวประชาชนต้องเป็นตัวเลขเท่านั้น'
    errVisitorInfoIdentityFormatNotValid = 'รูปแบบรหัสประชำตัวประชาชนไม่ถูกต้อง'

    errEmployeeIDNotFound = 'ไม่พบไอดีพนักงาน'
    errEmployeeIDNotNumber = 'ไอดีพนักงานต้องเป็นตัวเลขเท่านั้น'
    errEmployeeCodeNotFound = 'ไม่พบรหัสพนักงาน'
    errEmployeeFirstNameNotFound = 'ไม่พบชื่อพนักงาน'
    errEmployeeFitstNameProhibitSpecial = 'ชื่อพนักงาน ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errEmployeeLastNameNotFound = 'ไม่พบนามสกุลพนักงาน'
    errEmployeeLastNameProhibitSpecial = 'นามสกุลพนักงาน ห้ามมีอักขระพิเศษหรือช่องว่าง'

    errGetSlotVisitorNumberSiteIDNotFound = 'ไม่พบ site id'
    errGetSlotVisitorNumberSiteIDProhibitSpecial = 'site id ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errGetSlotVisitorNumberSiteIDNotNumber ='site id ต้องเป็นตัวเลขเท่านั้น'
    errGetSlotVisitorNumberSlotNumberNotFound = 'ไม่พบเลข Slot'
    errGetSlotVisitorNumberSlotNumberProhibitSpecial = 'เลข Slot ห้ามมีอักขระพิเศษหรือช่องว่าง'
    errGetSlotVisitorNumberSlotNumberNotNumber ='เลข Slot ต้องเป็นตัวเลขเท่านั้น'
    errGetSlotVisitorNumberIsFail = 'ไม่สามารถเรียกดู slot ที่ว่างได้'
    errGetSlotVistiorNumberNotValue = 'ไม่พบ Slot ว่าง'
}