version: '3'
services:

  api-bannayuu-visitor-inout:
    image: api-bannayuu-visitor-inout:1.0.0
    ports:
      - 36005:36005
    volumes:
      - ./volumes/log:/app/dist/logs
      - /home/ubuntu/banayuu_images:/home/ubuntu/banayuu_images
    restart: unless-stopped 
    environment:
      - TZ=Asia/Bangkok
      - NODE_ENV=development
      - APP_PORT=36005
      - DB_HOST=192.168.81.135
      - DB_PORT=50005
      - DB_NAME=demo_bannayuu_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=P@ssw0rd
      - IMAGE_PATH_WEB=/home/ubuntu/banayuu_images/webmanagement
      - IMAGE_PATH_VISITOR=/home/ubuntu/banayuu_images/visitor
      - MYCOMPANY_ID=1
      - IMAGE_SIZE_MB=10
      - URL_CALCULATE=http://172.25.30.64:36006/api/bannayuu/calculate/cal-all
      - HOST_LINE_NOTIFICATION=http://172.25.30.64:38502/apicross/webhook
      - PATH_LINE_ACTION_IN_NOTIFICATION=/push_noti_home_line
      - HOST_LINE_NOTIFICATION_BOARDCAST=http://172.25.30.64:38501/line_notify
      - PATH_LINE_ACTION_IN_NOTIFICATION_BOARDCAST=/push_notify_home_line
      - BASIC_AUTH_USERNAME=bannayuu
      - BASIC_AUTH_PASSWORD=bannayuu@pass
      - TOKEN_AUTHENTICATION=5330531265f44e00bffdd12aa1e3e3a0
    
    
      