module.exports = {
  apps: [
    {
      name: 'api-bannayuu-corporate-management',
      script: './dist/bannayuu-webmanagement-api.js',
      env: {
        NODE_ENV: 'production',
        APP_PORT:4090,
        DB_HOST:"local.uat.bannayuu.com",
        DB_PORT:5432,
        DB_NAME:"cit_bannayuu_db",
        DB_USERNAME:"cit",
        DB_PASSWORD:"db13apr",
        IMAGE_PATH_WEB:"C:\\Bannayuu\\Web\\Image\\files",
        IMAGE_PATH_VISITOR:"C:\\Bannayuu\\Visitor\\Image\\files",
        MYCOMPANY_ID:1,
        IMAGE_SIZE_MB:10,
        URL_CALCULATE:"http://localhost:4060/api/bannayuu/calculate/cal-all",
        HOST_LINE_NOTIFICATION:"https://cit.bannayuu.com/apicross/webhook",
        PATH_LINE_ACTION_IN_NOTIFICATION:"/push_noti_home_line",
        HOST_LINE_NOTIFICATION_BOARDCAST:"https://cit.bannayuu.com/apinotify/line_notify",
        PATH_LINE_ACTION_IN_NOTIFICATION_BOARDCAST:"/push_notify_home_line",
        BASIC_AUTH_USERNAME:"bannayuu",
        BASIC_AUTH_PASSWORD:"bannayuu@pass",
        TOKEN_AUTHENTICATION:"5330531265f44e00bffdd12aa1e3e3a0"
      },
      env_development: {
        NODE_ENV: "development",
        APP_PORT:36005,
        DB_HOST:"192.168.81.135",
        DB_PORT:50005,
        DB_NAME:"demo_bannayuu_db",
        DB_USERNAME:"postgres",
        DB_PASSWORD:"P@ssw0rd",
        IMAGE_PATH_WEB:"/home/ubuntu/banayuu_images/webmanagement",
        IMAGE_PATH_VISITOR:"/home/ubuntu/banayuu_images/visitor",
        MYCOMPANY_ID:1,
        IMAGE_SIZE_MB:10,
        URL_CALCULATE:"http://localhost:36006/api/bannayuu/calculate/cal-all",
        HOST_LINE_NOTIFICATION:"http://localhost:38502/apicross/webhook",
        PATH_LINE_ACTION_IN_NOTIFICATION:"/push_noti_home_line",
        HOST_LINE_NOTIFICATION_BOARDCAST:"http://localhost:38501/line_notify",
        PATH_LINE_ACTION_IN_NOTIFICATION_BOARDCAST:"/push_notify_home_line",
        BASIC_AUTH_USERNAME:"bannayuu",
        BASIC_AUTH_PASSWORD:"bannayuu@pass",
        TOKEN_AUTHENTICATION:"5330531265f44e00bffdd12aa1e3e3a0"
      },
    },
  ],
};
